//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentStudenttbl
    {
        public int Id { get; set; }
        public int ParentId { get; set; }
        public int StudentId { get; set; }
    
        public virtual Parentstbl Parentstbl { get; set; }
        public virtual Studentstbl Studentstbl { get; set; }
    }
}
