//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLeft
    {
        public int StudentId { get; set; }
        public Nullable<System.DateTime> DateLeft { get; set; }
    
        public virtual Student Student { get; set; }
    }
}
