//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentstbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Studentstbl()
        {
            this.AttendanceMarkingtbls = new HashSet<AttendanceMarkingtbl>();
            this.Leavestbls = new HashSet<Leavestbl>();
            this.Markingstbls = new HashSet<Markingstbl>();
            this.ParentStudenttbls = new HashSet<ParentStudenttbl>();
            this.StudentClasstbls = new HashSet<StudentClasstbl>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegistrationNumber { get; set; }
        public string Username { get; set; }
        public string StdPassword { get; set; }
        public string CNIC { get; set; }
        public int ApprovalStatusId { get; set; }
        public int ActiveStatusId { get; set; }
    
        public virtual ActiveStatustbl ActiveStatustbl { get; set; }
        public virtual ApprovalStatustbl ApprovalStatustbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AttendanceMarkingtbl> AttendanceMarkingtbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Leavestbl> Leavestbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Markingstbl> Markingstbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentStudenttbl> ParentStudenttbls { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentClasstbl> StudentClasstbls { get; set; }
        public virtual StudentLefttbl StudentLefttbl { get; set; }
    }
}
