//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSchoolSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTabletbl
    {
        public string WeeksDay { get; set; }
        public int ClassId { get; set; }
        public int SubjectId { get; set; }
        public System.TimeSpan LectureTime { get; set; }
    
        public virtual Classtbl Classtbl { get; set; }
        public virtual Subjectstbl Subjectstbl { get; set; }
    }
}
